### ISSUE TITLE
Investigar y crear FAST API para todas operaciones de Celery y Redis

### ISSUE THREAD

**Issue by ILMPI** [teamVoltix/voltix-back#13]

**Comment by EIAHRJAY** [comment]
1. Celery y Redis en un solo microservicio
Puedes crear un microservicio que se encargue exclusivamente de manejar las tareas asíncronas usando Celery y Redis. Este enfoque es útil si planeas mantener toda la lógica de tareas en un único lugar para centralizar el procesamiento de tareas en segundo plano.

Estructura básica:

Microservicio de Celery:
Incluye Celery configurado para conectar a un broker (Redis) y un backend (puede ser Redis o algo como PostgreSQL).
Define las tareas asíncronas que otros microservicios pueden ejecutar.
Este microservicio consume mensajes enviados al broker y realiza el trabajo correspondiente.
Ventajas:

Separación clara de responsabilidades para las tareas en segundo plano.
Redis se usa como broker y/o backend para Celery, pero no necesitas otro microservicio exclusivo para Redis.
2. Microservicio dedicado para Redis
Si Redis tiene un rol más allá de ser un broker para Celery (como almacenar datos en memoria temporalmente o gestionar estados rápidos), podrías crear un microservicio para Redis y otro separado para Celery.

Estructura básica:

Microservicio de Redis:
Proporciona acceso a datos en memoria, por ejemplo, caché de sesiones o datos temporales.
Puede estar aislado si Redis se utiliza con otras aplicaciones o servicios además de Celery.
Microservicio de Celery:
Enfocado exclusivamente en la ejecución de tareas asíncronas.
Se conecta al microservicio de Redis como broker.
Ventajas:

Redis puede usarse de forma independiente para otras funcionalidades (cache, colas, etc.).
Mayor flexibilidad si Redis es esencial para más de un contexto.

**Comment by EIAHRJAY** [comment]
1. Caché de respuestas
Almacena las respuestas de la API para reducir el tiempo de procesamiento en solicitudes repetidas. Esto es útil si tienes datos que no cambian frecuentemente.

Ejemplo:

Caché de resultados de consultas costosas a la base de datos.
Caché de datos obtenidos de servicios externos (APIs de terceros).
Cómo funciona:

Antes de procesar una solicitud, verifica si el resultado ya está en Redis.
Si está, lo devuelves directamente; si no, lo procesas y lo guardas en Redis para futuras solicitudes.
2. Almacenamiento de sesiones
Redis se puede usar como un almacenamiento rápido y eficiente para sesiones de usuarios en sistemas de autenticación.

Ejemplo:

Guardar tokens de sesión para usuarios logueados.
Gestionar datos temporales de usuarios, como carritos de compra o datos de formularios incompletos.
3. Gestión de colas (más allá de Celery)
Redis puede manejar colas de tareas o eventos en tiempo real, independientemente de Celery.

Ejemplo:

Sistema de notificaciones en tiempo real.
Manejo de mensajes en una arquitectura de event-driven (actividades disparadas por eventos).
4. Rate Limiting
Puedes usar Redis para limitar la cantidad de solicitudes que un usuario puede realizar en un período de tiempo, implementando políticas de rate limiting.

Ejemplo:

Permitir solo 100 solicitudes por minuto para un usuario específico.
Prevenir abusos o ataques DDoS a tu API.
Cómo funciona:

Redis almacena un contador por cada IP o usuario.
Se verifica y actualiza en cada solicitud.
5. Publicación y suscripción (Pub/Sub)
Redis incluye un sistema de Pub/Sub que permite manejar comunicación en tiempo real entre servicios.

Ejemplo:

Notificaciones push.
Actualización de datos en tiempo real (por ejemplo, actualizaciones de estado en un dashboard).
6. Almacenamiento temporal
Puedes usar Redis para almacenar datos temporales que solo necesitas durante un corto período.

Ejemplo:

OTP (códigos de verificación) para autenticación de dos factores.
Enlace temporal para restablecimiento de contraseña.
Datos de procesamiento intermedio en flujos complejos.
7. Procesamiento de métricas o contadores
Redis es ideal para contar eventos rápidamente, como visitas a endpoints o interacciones en tu aplicación.

Ejemplo:

Contador de vistas de página.
Seguimiento de eventos como clics o interacciones de usuarios.
